### ISSUE TITLE
Entries out of order in future log

### ISSUE THREAD

**Issue by aasemfituri** [cse110-sp21-group5/cse110-sp21-group5#41]
**Part of project**
What part of the project are you working on when you ran into the bug?
Future log

**Describe the bug**
The entries are sometimes out of order.

**To Reproduce**
1. Go to the future log.
2.  Make an entry for June.
3.  Make another entry for July.
4.  Make one last entry for November.
5.  For some reason, November shows up as the first month in the list.

**Expected behavior**
November should be at the end (or equivalently November is at the top followed by July then June).

**Additional context**
I think it has to do with addEntryToDB() and how you are storing the keys.

**Comment by BNLonc** [comment]
Resolved. The function isLaterThan was comparing the string values of the numbers 6, 7, and 11, and concluding that 11 was the least of them by string comparison.
